name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                include:
                    - os: ubuntu-latest
                      platform: linux

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2 # Install pnpm using packageManager key in package.json

            - name: Use Node.js 18.18.2
              uses: actions/setup-node@v3
              with:
                  node-version: 18.18.2
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Run Electron Builder
              run: |
                  pnpm electron-builder --${{ matrix.platform }} --publish never
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CSC_LINK: ${{ secrets.APPLE_SIGNING_CERT }} # Only relevant on macOS
              if: ${{ matrix.platform == 'mac' || matrix.platform == 'linux' || matrix.platform == 'windows' }}

            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: ${matrix.platform}-build
                  path: |
                    dist/*.*
                    release/**/*
